# Generated by Django 4.0 on 2022-01-06 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productsapp', '0003_category_owner_supplier_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='Product Name',
            field=models.CharField(db_column='name', max_length=512, verbose_name='Product Name'),
        ),
    ]
