# Generated by Django 4.0 on 2022-01-06 06:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('productsapp', '0004_alter_product_product name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category_id',
        ),
        migrations.RemoveField(
            model_name='product',
            name='supplier_id',
        ),
        migrations.AddField(
            model_name='product',
            name='Product Category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='productsapp.category', verbose_name='Product Category'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='Product Supplier',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='productsapp.supplier', verbose_name='Product Supplier'),
            preserve_default=False,
        ),
    ]
