# Generated by Django 4.0 on 2021-12-29 05:18

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Customer Group Name', models.CharField(db_column='name', max_length=512, verbose_name='Customer Group Name')),
            ],
            options={
                'db_table': 'customer_group',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First Name', models.CharField(db_column='first_name', max_length=512, verbose_name='First Name')),
                ('Last Name', models.CharField(db_column='last_name', max_length=512, verbose_name='Last Name')),
                ('address', models.TextField()),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('email', models.EmailField(max_length=254)),
                ('group_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customersapp.customergroup')),
            ],
            options={
                'db_table': 'customer',
                'managed': True,
            },
        ),
    ]
