# Generated by Django 4.0 on 2021-12-30 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customersapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'managed': True, 'verbose_name': 'Customer', 'verbose_name_plural': 'Customers'},
        ),
        migrations.AlterModelOptions(
            name='customergroup',
            options={'managed': True, 'verbose_name': 'Customer Group', 'verbose_name_plural': 'Customer Groups'},
        ),
        migrations.AlterField(
            model_name='customer',
            name='address',
            field=models.TextField(blank=True),
        ),
    ]
