# Generated by Django 4.0 on 2022-01-06 05:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('customersapp', '0002_alter_customer_options_alter_customergroup_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='owner',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='customers', to='auth.user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customergroup',
            name='owner',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='customer_groups', to='auth.user'),
            preserve_default=False,
        ),
    ]
