# Generated by Django 4.0 on 2022-01-10 04:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customersapp', '0003_customer_owner_customergroup_owner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customergroup',
            old_name='Customer Group Name',
            new_name='customer_group_name',
        ),
    ]
