# Generated by Django 4.0 on 2022-01-10 05:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('customersapp', '0004_rename_customer group name_customergroup_customer_group_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customergroup',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customer_groups', to='auth.user'),
        ),
    ]
