# Generated by Django 4.0 on 2022-01-10 11:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('customersapp', '0005_alter_customergroup_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customergroup',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='customer_groups', to='auth.user'),
            preserve_default=False,
        ),
    ]
